### ISSUE TITLE
Error when formatting LaTeX fit results for a parameter-less function

### ISSUE THREAD

**Issue by alexpearce** [iminuit/iminuit#191]
## Failing test case

```python
from iminuit import Minuit

def f():
    return 1

m = Minuit(f)
m.migrad()
```

## Output when run in a Jupyter notebook

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-733ac93d5851> in <module>()
      5 
      6 m = Minuit(f)
----> 7 m.migrad()

/Users/apearce/Code/iminuit/iminuit/_libiminuit.pyx in iminuit._libiminuit.Minuit.migrad (iminuit/_libiminuit.cpp:5910)()
    490 
    491         if self.print_level > 0:
--> 492             self.print_fmin()
    493 
    494         return self.get_fmin(), self.get_param_states()

/Users/apearce/Code/iminuit/iminuit/_libiminuit.pyx in iminuit._libiminuit.Minuit.print_fmin (iminuit/_libiminuit.cpp:10412)()
    738         self.frontend.print_hline()
    739         self.frontend.print_fmin(sfmin, self.tol, ncalls)
--> 740         self.print_param()
    741         self.frontend.print_hline()
    742 

/Users/apearce/Code/iminuit/iminuit/_libiminuit.pyx in iminuit._libiminuit.Minuit.print_param (iminuit/_libiminuit.cpp:9295)()
    687             return
    688         p = self._prepare_param()
--> 689         self.frontend.print_param(p, self.merrors_struct, **kwds)
    690 
    691     def latex_param(self):

/Users/apearce/Code/iminuit/iminuit/frontends/html.py in print_param(self, mps, merr, float_format, smart_latex, latex_map)
    211         ltable = LatexFactory.build_param_table(mps, merr,
    212                                                 float_format=float_format, smart_latex=smart_latex,
--> 213                                                 latex_map=latex_map)
    214 
    215         # rows = str(ltable).count('\n')+1

/Users/apearce/Code/iminuit/iminuit/latex.pyc in build_param_table(cls, mps, merr, float_format, smart_latex, latex_map)
    189         alignment = '|c|r|r|r|r|r|r|r|c|'
    190         ret = LatexTable(data, headers=headers, alignment=alignment,
--> 191                          smart_latex=smart_latex, latex_map=latex_map)
    192         ret.float_format = float_format
    193         return ret

/Users/apearce/Code/iminuit/iminuit/latex.pyc in __init__(self, data, headers, smart_latex, escape_under_score, alignment, rotate_header, latex_map)
     34                  latex_map=None):
     35         if headers is not None:
---> 36             assert (len(headers) == len(data[0]))
     37 
     38         self.headers = headers

IndexError: list index out of range
```

## Output when run as a script with `python`

```
Traceback (most recent call last):
  File "ffff.py", line 7, in <module>
    m.migrad()
  File "iminuit/_libiminuit.pyx", line 492, in iminuit._libiminuit.Minuit.migrad (iminuit/_libiminuit.cpp:5910)
    self.print_fmin()
  File "iminuit/_libiminuit.pyx", line 740, in iminuit._libiminuit.Minuit.print_fmin (iminuit/_libiminuit.cpp:10412)
    self.print_param()
  File "iminuit/_libiminuit.pyx", line 689, in iminuit._libiminuit.Minuit.print_param (iminuit/_libiminuit.cpp:9295)
    self.frontend.print_param(p, self.merrors_struct, **kwds)
  File "/Users/apearce/Code/iminuit/iminuit/frontends/console.py", line 112, in print_param
    maxlength = max([len(x) for x in vnames])
ValueError: max() arg is an empty sequence
```

The test case passes if the function `f` has at least one argument, e.g. `def f(x):`.

**Comment by cdeil** [comment]
I checked locally, these errors are gone in `master` now that #192 is merged.

@alexpearce - Thanks!
